### ISSUE TITLE
Opera docs/tests

### ISSUE THREAD

**Issue by slwu89** [Merck/AlgebraicAgents.jl#13]
Hi @thevolatilebit! My next plan is to write some tests/documentation for the Opera structure. I'm opening this issue and will close it when I've merged PR(s) that fulfill those goals.

I first had a few questions:

1. Is it possible to do something like this using the Opera interface: agent A sends information to agent B a deterministic number of time steps from now?
2. What is a use case for `_interact!` ?
3. Similarly, what is the main difference in use cases between `schedule_call` and `schedule`?

**Comment by thevolatilebit** [comment]
Thank you for opening this!

**ad 1:** I don't think so. So far, all interactions (either `schedule` or `schedule_call`) will be executed in the same *time* step as they were scheduled (the execution takes place after we sort out all the calls to `_step!`), in the order of their priorities (implemented as a priority queue). It should be straightforward to implement delayed interactions as well.

**ad 2-3:** `_interact!` (scheduled via `schedule`) simply "pokes" an agent; a use case: a reactor overheats and tells the control tower to "wake up" and take an action. It doesn't suggest any particular action; it's up to the control tower to find out what's going on. In contrast, you may use `schedule_call` to invoke a particular action (a reactor overheats and calls `start_cooling!(control_tower, actual_temp)`.
