### ISSUE TITLE
ci (tests, docs, tagbot)

### ISSUE THREAD

**Issue by thevolatilebit** [Merck/AlgebraicAgents.jl#14]
It would be great to automatise docs deployment, add build and code coverage tests, etc. This would apply to our other projects as well.

Status:
- [x] tests;
- [x] docs deployment;
- [x] tagbot;
- [x] formatter;
- [x] compat.

**Comment by slwu89** [comment]
Cool! This is a good idea. What platform do you think is best to use for code cov tests? I have used codecov.io for R packages on GitHub before, but I'm not certain whats the easiest to use for Julia.

**Comment by thevolatilebit** [comment]
I would suggest [Coverage.jl](https://github.com/JuliaCI/Coverage.jl) + [codecov.io](codecov.io)

Maybe docs deployment would be a good start?

**Comment by thevolatilebit** [comment]
docs, tagbot, compat, tests https://github.com/Merck/AlgebraicAgents.jl/commit/3694b0e7deda68d60cecbdca50b51c9a5d82186d

**Comment by thevolatilebit** [comment]
formatter https://github.com/Merck/AlgebraicAgents.jl/commit/2950bf0e6ad903d0f63f9a3732204f4451d1b5ce
