### ISSUE TITLE
suggestion for `getobservable`

### ISSUE THREAD

**Issue by slwu89** [Merck/AlgebraicAgents.jl#32]
Currently the indexing operator forwards to `getobservable`. I've noticed in practical modeling however, we haven't used `getobservable` very often (and when we do, it's not too much of an annoyance to type out `getobservable(agent, keys)`). However, in projects, we often have code like `inners(depot)["inventory"]`, or similar lines, appearing throughout the codebase repeatedly. What do you think of changing `Base.getindex` to instead forward to `inners(agent)[keys...]`?

**Comment by thevolatilebit** [comment]
Thank you! I've also been considering the same thing for a while, but I haven't been very determined to make the design change. Ok, we will change this.

**Comment by slwu89** [comment]
Ok, glad to hear you have the same opinion! I'll go ahead and make the change and submit a PR.
