### ISSUE TITLE
mutability of agent structs

### ISSUE THREAD

**Issue by slwu89** [Merck/AlgebraicAgents.jl#4]
Any agent type being made from calling `@aagent` is mutable, but with Julia versions >= 1.8 now we can specify particular fields as being `const`, which can help bring performance closer to immutable structs (see https://docs.julialang.org/en/v1/manual/types/#Mutable-Composite-Types). It would be nice to let users to specify fields as `const` if they like, to improve performance. I'll look into how to make this work with the macros. Alternatively I can also look into how to replicate the functionality with standard functions.

**Comment by thevolatilebit** [comment]
I completely agree. Since the `@agent` macro is anyway taken from https://github.com/JuliaDynamics/Agents.jl/blob/f05a17aca2242df26423df1dc890f10d150658b1/src/core/agents.jl#L168, I am sure that solving this issueI would bring double benefit to both Agents.jl and AlgebraicAgents.jl!

**Comment by thevolatilebit** [comment]
The agent macro syntax

```julia 
@agent name supertype begin
    fields
end
```

is a bit unfortunate, as it is impossible to pass `const field` in the extra fields body. Therefore, I suggest that we move to a syntax which is more aligned with Julia constructors

```@agent supertype struct agent
   fields
```

**Comment by thevolatilebit** [comment]
https://github.com/Merck/AlgebraicAgents.jl/pull/6

**Comment by thevolatilebit** [comment]
feel free to reopen
