### ISSUE TITLE
undefined additional fields

### ISSUE THREAD

**Issue by slwu89** [Merck/AlgebraicAgents.jl#5]
If we make a new agent type with `@aagent` which has new additional data fields and construct it and print it to the REPL the `Base.show` method will try to show it with undefined memory which doesn't cause a problem for the program (it keeps running) but results in an error message. We may want to keep this behavior to remind users that they need to manually need to initialize memory because of the way the macros work. I'm just flagging it as potentially worthy of a quick discussion.

MWE:

```julia
julia> using AlgebraicAgents
julia> @aagent MyAgent begin
           myname::String
       end

julia> MyAgent("Alice")
agent Alice with uuid 7d15f2a3 of type MyAgent 
   custom properties:Error showing value of type MyAgent:
ERROR: UndefRefError: access to undefined reference
Stacktrace:
```

**Comment by thevolatilebit** [comment]
That's a good point! Indeed, the constructors defined by `@aagent` are "unsafe".

My intention was to provide a partial initialisation of the the agent struct; that is, the constructor populates the common interface fields including `parent`, `directory`, `relpathrefs`, and `opera`. A user is then expected to fill the additional fields in a custom, "outer" constructor.

**Comment by thevolatilebit** [comment]
Anyway, the constructor provided by `@aagent` will now require the agent's name and extra fields by default. It will still initialise the common interface fields.

It is still possible to define new agent types directly or provide custom agent macro (using `define_agent`).

Feel free to reopen.
